repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
    - id: mypy
      args: [--pretty]
      additional_dependencies: [
        "attrs==23.1.0",
        "pyyaml==6.0.1",
        "cattrs==23.2.3",
        "rich==13.7.0",
        "typeguard==4.1.5",
        "types-pyyaml==6.0.12.11",
        "GitPython==3.1.43"
      ]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [--select, I, --fix]
    # Run the formatter.
    - id: ruff-format
