[tool.poetry]
name = "bpy-build"
version = "0.1.0"
description = "A build system to make building and testing Blender addons 10 times easier`"
authors = ["StandingPad"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8.1"
pyyaml = "^6.0"
rich = "^13.3.5"

[tool.poetry.dev-dependencies]
black = "^23.3.0"

[tool.poetry.scripts]
bpy-build = "bpy_build:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
