[tool.poetry]
name = "bpy-addon-build"
version = "0.1.4"
description = "A build system to make building and testing Blender addons 10 times easier"
authors = ["StandingPad"]
license = "MIT"
homepage = "https://github.com/StandingPadAnimations/bpy-build"

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^6.0"
rich = "^13.3.5"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]
black = "^23.3.0"

[tool.poetry.scripts]
bpy-addon-build = "bpy_addon_build:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
